### ISSUE TITLE
error messages disappear too fast when trying to start stream 

### ISSUE THREAD

**Issue by xaxxon** [bastimeyer/livestreamer-twitch-gui#285] opened 2016-08-08 21:46 UTC
*Thanks for reporting an issue!*
*Please read the contribution guidelines first!*

*Feel free to use the following template. Be as detailed as possible.*
*Don't forget to remove this text before submitting.*

----

### Description

When starting a stream that isn't available, the error message disappears too quickly to catch it.   

It took me 4 tries before I was able to capture this: http://i.imgur.com/9AkGPJE.png

### Expected / Actual behavior

Actually show the error message long enough to read it.

### Reproduction steps

1. ...
2. ...
3. ...

### Environment details (operating system, etc.)

os x

### Comments, logs, screenshots, etc.

...

**Comment by bastimeyer** [comment] 2016-08-08 22:10
This has nothing to do with streams not being available. See #283. The issue has already been fixed and a new release has also already been uploaded.

The popup automatically closes when the spawned livestreamer child process unexpectedly terminates. The GUI doesn't know about this specific livestreamer failure and doesn't show an error message, since stream qualities usually don't change.
I'm going to change the behavior of the stream popups once VOD support has been implemented, because I will need to rewrite the stream launch logic for this as well.

Closing this now, since it's actually a duplicate of #283

**Closed by bastimeyer** 2016-08-08 22:10 UTC
