### ISSUE TITLE
Window is blank when it re-opens after being minimized to tray after a stream is closed

### ISSUE THREAD

**Issue by MoonSha** [bastimeyer/livestreamer-twitch-gui#236] opened 2016-04-05 18:39 UTC
After watching and then closing a stream with the program minimised to the Tray, the gui will pop-up like it's supposed to but the screen is blank, as in the picture. If I right click the icon in the Tray and select "Toggle Window" the gui will return to normal and works as expected.

-

Reproduction steps
1. Open a stream
2. Manually click minimise button on twitch-gui with the option "Minimize button" checked on "Minimize to tray"
3. Close stream
4. twitch-gui re-opens but screen is blank.

Windows 7 64bit, problem appeared after updating to 0.13.0 of the twitch gui.

...

![twitchgui](https://cloud.githubusercontent.com/assets/11814582/14293611/afb06db2-fbb0-11e5-9b04-37e48452365e.png)

**Comment by bastimeyer** [comment] 2016-04-05 19:50
I can't reproduce this. This also looks like an issue with NW.js and not with the application itself...
Did you try deleting the application folder before extracting the archive? You should also try to delete your config folder in `%LOCALAPPDATA%\livestreamer-twitch-gui` and then test it again.

**Comment by MoonSha** [comment] 2016-04-05 21:32
So I tried, deleting the appdata folder which reset settings. I then just turned on the settings concerned with minimising the program and it acted the same. I also tried changing to the 32bit version but it acts the exact same. If I tell the program to "move to tray" on playing, it will open back up just fine after a stream is closed.

I also downgraded to 12 and it acts the same, not sure if I just didn't use the minimise feature before or I somehow broke something but it definitely appeared after updating to 13.

**Comment by bastimeyer** [comment] 2016-04-06 15:09
There's an open issue in the NW.js repo (nwjs/nw.js#3419) and the reason for such a black screen is unknown. This might be fixed by the newest NW.js release `v0.13.x`. An upgrade to it is not possible right now, though...

Someone said that this black screen would only appear if he is using other NW.js apps at the same time, like popcorntime, etc. Maybe that's the issue here or something else on your system. *Broken* graphics drivers were also mentioned.

**Comment by bastimeyer** [comment] 2016-04-27 10:04
Closing this, since I'm unable to reproduce this. This might be fixed by a NW.js upgrade...

**Closed by bastimeyer** 2016-04-27 10:04 UTC

**Comment by Augures01** [comment] 2020-09-15 08:26
@bastimeyer 
Hi! I did some investigations about this issue (cause it annoying me for a few years)

Settings - GUI - OS Integration
If I choose "Tray", minimize window to tray, after opening Streamlink GUI works as expected
But if I choose "Both" and minimize to tray, after opening GUI, it freezing (or black screen like in this issue) until some interactions (move or resize window, for example)

I can record video if needed

**Comment by bastimeyer** [comment] 2020-09-15 11:19
@Augures01 Please don't necro-bump issues that are more than four and a half years old. If you're seeing a black screen, please read this thread #669 first. Regarding what you've said with minimize to tray, [there isn't a difference between those two methods](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.10.0/src/app/services/nwjs.js#L66-L80) in the application logic, and seeing a black screen can't be caused by application logic in a Chromium context anyway.
If you have more details, please create a new issue and fill in all the required informations.
