### ISSUE TITLE
Closing  a stream from the GUI doesn't actually close it

### ISSUE THREAD

**Issue by MomoGunz** [bastimeyer/livestreamer-twitch-gui#264] opened 2016-06-29 03:04 UTC
## Description

When you want to close Livestreamer from the livestreamer-twitch-gui GUI, it removes the stream from the currently watched streams but does not actually close Livestreamer or mpv.

### Expected / Actual behavior

The GUI should close the Livestreamer.exe and/or mpv.exe processes.

### Reproduction steps

1. Open a stream
2. Close it from the "Close stream" button

### Environment details (operating system, etc.)

Windows 10 x64, mpv video player

**Comment by bastimeyer** [comment] 2016-06-29 09:29
I can't reproduce this...

This is what happens when you click the close stream button in the GUI:
1. [Trigger the shutdown action on the ModalLivestreamerComponent](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/06b20e115836c0224586770033ffa9332d22aa39/src/templates/components/modal/ModalLivestreamerComponent.hbs#L37)
2. [Call kill() on the currently active Livestreamer model](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/06b20e115836c0224586770033ffa9332d22aa39/src/app/components/modal/ModalLivestreamerComponent.js#L64-L70)
3. [Kill the child process attached to the model](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/06b20e115836c0224586770033ffa9332d22aa39/src/app/models/Livestreamer.js#L46-L51)
4. [Execute the onExit event listener of the child process](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/06b20e115836c0224586770033ffa9332d22aa39/src/app/services/LivestreamerService.js#L363-L377)
5. [Destroy the Livestreamer model and remove it from the data store](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/06b20e115836c0224586770033ffa9332d22aa39/src/app/services/LivestreamerService.js#L212-L232)

The list of currently watched streams actually counts all Livestreamer models in the store (and the running livestreamer child processes), so there is no way that a livestreamer child process keeps running while it's not shown in the GUI.

Livestreamer may only keep running if it's ignoring the SIGTERM message from the GUI. If a video player remains after the livestreamer process has been killed, then it's either Livestreamer's fault for not sending another SIGTERM message to the player or it's the fault of the player for ignoring this message (VLC does this in its default configuration).

Since you are running Windows, I am wondering if you've installed Livestreamer via Python's pip. This is known for causing weird behavior of the livestreamer executable and you should do what the README says and use the regular Livestreamer installer...

**Comment by MomoGunz** [comment] 2016-06-29 10:00
You were right about me not using the regular Livestreamer installer.

I did as you said and installed it the regular way but the bug is still here. Here is a gif of it : https://gfycat.com/AliveLoathsomeBellsnake

It might not be related but is it a normal behaviour for the GUI to not close the previous player when changing the stream quality ?

**Comment by bastimeyer** [comment] 2016-06-29 10:37
This is not a bug of the GUI. It is not responsible for the player, this is Livestreamer's business...

Like I've said, some players can not be closed by Livestreamer if those are ignoring Livestreamer's SIGTERM signal.
In your case though, it seems like you've selected HLS as stream type (`--player-passthrough`). By using HLS, Livestreamer will just pass over Twitch's HLS URL to the player and will completely ignore the spawned player process when it's being killed by the GUI. You can read more [in the wiki](https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Livestreamer-configuration)... Just select HTTP or RTMP as stream type.

*Also, please don't call it gif, it's a webm video using the VP8 codec, this always triggers me when I'm reading this on reddit* :stuck_out_tongue_winking_eye:

**Comment by MomoGunz** [comment] 2016-06-29 10:59
I love the level of details in the wiki, my bad for not reading all of it before posting here.

I actually can't change the Livestreamer stream type even though I changed it to rtmp or http in the settings and restarted the GUI.
I also tried to launch a Twitch stream via rtmp through the Livestreamer CLI but it always selects the hls source.
Could you help me out once more please ?

Will do, I'm not used to call them webm's!

**Comment by bastimeyer** [comment] 2016-06-29 11:29
>I also tried to launch a Twitch stream via rtmp through the Livestreamer CLI but it always selects the hls source.

Do you have a custom `livestreamerrc` config file?
[See the livestreamer documentation...](http://docs.livestreamer.io/cli.html#configuration-file)

Even if you have a config file which sets the [`player-passthrough`](http://docs.livestreamer.io/cli.html#cmdoption--player-passthrough) method, the GUI will always use the `--player-passthrough` parameter, which overrides potential misconfigurations in the `livestreamerrc` config file, meaning that the GUI settings are *final*. I have no idea why livestreamer would choose a different method.

If this doesn't work:
`livestreamer -p /path/to/player --player-passthrough rtmp twitch.tv/CHANNEL best`

...then maybe your previous Livestreamer installation was messed up and you should remove everything first and install it again.

**Comment by MomoGunz** [comment] 2016-06-29 11:54
My `livestreamerrc` config file is the default one.

I will continue to look for the issue on my own as this is far from the original issue and beyond your scope of support.

Thank you very much for your quick replies and for your work, keep it up !

**Comment by MomoGunz** [comment] 2016-06-29 13:41
### Description

I opened an issue on the Livestreamer GitHub project and I have been told that Twitch streams are almost exclusively hls https://github.com/chrippa/livestreamer/issues/1368#issuecomment-229346079
This would explain the issue I submitted earlier today https://github.com/bastimeyer/livestreamer-twitch-gui/issues/264#issuecomment-229324420

### Comments, logs, screenshots, etc.

https://gyazo.com/ac00c9ef72b67cbf4248bae5ec83998d

The Livestreamer stream type option seems to be currently useless.
Is there a way to close the player from the GUI while having a hls stream ?

**Comment by bastimeyer** [comment] 2016-06-29 14:12
Yes, Twitch streams are all in the HLS format, as stated in the wiki. Also, as stated in the wiki as well, Livestreamer reads these HLS streams, buffers the stream video/audio data and outputs another **different** stream either via stdout, a named pipe, http or rtmp. Stdout and named pipes are not used by the GUI, because there are players which are unable to read from stdin and having http as default option is the best *compromise*...

The `--stream-type` parameter is completely useless, since it's just filtering all possible **input** stream types.

As I've already said earlier, by using `--player-passthrough hls`, Livestreamer will just grab the HLS url from Twitch and pass it directly to the player, ignoring everything else. You can use this for Twitch VODs, so you're able to jump around in the timeline in your video player. Also, Livestreamer will not close the player in this scenario, because it's only job was getting the HLS url.

---

The passthrough option in the GUI may be improved in the future when other features like VODs or video downloading will be implemented, but other than that, there's nothing to be fixed or changed for now.

**Comment by skulblakka** [comment] 2016-06-29 14:53
I can confirm that the stream is not closing when using the git/pip version. 

Looking at the program with debugging enabled the problem seems that the livestreamer.exe is immediately closed and a python.exe or pythonw.exe process is created instead. The GUI is not aware of this change and closes the no longer existing livestreamer.exe process. 

I'm not sure if there is a way to find out the PID of the python process to close it instead of the livestreamer process.

**Closed** 2016-06-29 21:56 UTC

**Comment by MomoGunz** [comment] 2016-06-29 22:08
Everything is now working as intended.
Unfortunately, I have no idea what was the issue as I literally changed nothing since earlier today.
