### ISSUE TITLE
livestreamer-twitch-gui not working with MPC HC

### ISSUE THREAD

**Issue by Kaze79** [bastimeyer/livestreamer-twitch-gui#263] opened 2016-06-28 15:26 UTC
### Description

When I use the Twitch GUI with the MPC HC it doesn't work. I click on a stream, the playe opens and then nothing. If I press Play it writes Opening... but nothing ever happens. Also it seems weird that if I close the player, the GUI still has the stream popup as if I didn't close the media player already. This doesn't happen with VLC (when I close VLC, that popup closes too). The weird thing is if I launch it through cmd `livestreamer twitch.tv/beyondthesummit best --player "C:/Program Files/MPC-HC/mpc-hc64.exe"` it works fine.

### Expected / Actual behavior

Expected:

- click on stream in twitch gui
- popup
- player opens and streams starts running
- close the player
- popup closes

Actual:

- click on stream in twitch gui
- popup
- player opens and nothing happens
- twitch gui doesn't register closure of player

### Environment details (operating system, etc.)

Windows 10 64-b Edu version, 64b version of MPC HC, livestreamer, twitch gui and player up to date.

**Comment by bastimeyer** [comment] 2016-06-28 16:25
**Are you using custom player arguments?**

This could prevent the GUI from launching the player. Please read the [wiki](https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Player-configuration)...

**Which stream type do you have selected?**

The default bahavior of Livestreamer is passing the stream data to the player via `stdin` (see your command line). The GUI on the other hand is using the [`--player-passthrough`](http://docs.livestreamer.io/cli.html#cmdoption--player-passthrough) parameter of livestreamer (see the [wiki](https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Livestreamer-configuration)). MPC-HC shouldn't have problems reading from `HTTP`, `RTMP` or `HLS`, though.

Please run these commands and check if this works as well:
```
livestreamer twitch.tv/beyondthesummit best --player-passthrough http --player "C:/Program Files/MPC-HC/mpc-hc64.exe"
livestreamer twitch.tv/beyondthesummit best --player-passthrough rtmp --player "C:/Program Files/MPC-HC/mpc-hc64.exe"
livestreamer twitch.tv/beyondthesummit best --player-passthrough hls  --player "C:/Program Files/MPC-HC/mpc-hc64.exe"
```

The popup will close as soon as the livestreamer process is being killed. When using HLS as stream type, livestreamer will not detect the shutdown of the player process and will keep running as long as you press the close button inside the GUI. This can't be fixed...

**Comment by Kaze79** [comment] 2016-06-28 16:59
That Wiki kinda does nothing, those options are additional options, from what I understood, neither of those two options are mandatory.

All three work for HC, `hls` doesn't work for BE (`Cannot render file.`). 

Tried adding `--player-passthrough http` into Custom Paramters, still the same - player opens, nothing happens.

**Comment by bastimeyer** [comment] 2016-06-28 19:09
Since you didn't answer my two questions explicitly, I guess custom player arguments are not set and you aren't using the HLS value. Good, this is not the source of the issue then...

> Tried adding --player-passthrough http into Custom Paramters

Don't set custom livestreamer parameters which are being used by the GUI, or else they will be used twice and yours will be overridden. The player passthrough option is hidden behind the advanced settings (at the top), and the default value is http.

> All three work for HC

Well, the `--player-passthrough` parameter is the only different param the GUI is using compared to your first command line (ignoring some other unimportant ones). Are you sure that you have set the correct path to the player executable in the GUI?

Since the GUI doesn't log the used livestreamer command line, you could try to debug the latest version from the master branch and get the exact parameter list the GUI is creating for you, so you can test it again. If the GUI creates a correct parameter list, everything else that happens is *GUI unrelated* and the issue is somewhere else.
Build instructions can be found [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/master/CONTRIBUTING.md#developing-and-building) and a breakpoint needs to be set [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/06b20e115836c0224586770033ffa9332d22aa39/src/app/services/LivestreamerService.js#L359), so the `params` var can be read.

**Comment by Kaze79** [comment] 2016-06-28 19:28
That link to wiki of yours doesn't have anything. It only has a link that leads to  --player-args documentation...and that page is empty. So no I did not set custom parameters up.

Yes. And I have tried http, rtmp and hls. Nothing worked.

Yes. `C:\Program Files\MPC-BE x64\mpc-be64.exe` to be exact. Also, the player starts so the address is correct, the player just doesn't do anything.

Anyway, before I dive into debugging, are those commands for Windows?

**Comment by bastimeyer** [comment] 2016-06-28 20:27
> That link to wiki of yours doesn't have anything.

Thanks... The documentation URL was changed recently, but it's fixed now in the wiki...

> Anyway, before I dive into debugging, are those commands for Windows?

All commands are the same and work on all platforms...
Before you start debugging, you should check the running process and used parameters after launching a stream. On Windows you must enable the command line column first in the task manager.

> whether I use stdin or --player-passthrough

The GUI doesn't have an option for passing stream data to the videoplayer via stdin, as it's not supported by every player. This may be changed in the future, though, with predefined player argument lists and stream downloading...

**Closed** 2016-07-11 11:17 UTC
