### ISSUE TITLE
"Launching stream" popup staying up

### ISSUE THREAD

**Issue by speccer** [bastimeyer/livestreamer-twitch-gui#38] opened 2015-01-27 19:04 UTC
I prefer to have the option "Hide the popup on success" checked. Prior to release v0.7.0, the "Preparing"->"Launching Stream" popup would close itself once the stream launched. After updating, the popup will remain until the triggering stream is closed, or until I hit the close button on the popup itself. This is a minor inconvenience when going to open a second stream.

When updating, I simply renamed the old folder and put the new folder in its place. It seemed to retain its settings, though I did need to log back in at one point.

To troubleshoot, I disabled the "Hide the popup on success" option. While this was in effect, the popup stayed at "Launching stream" and did not progress to giving me the option to open chat, etc. Toggling the "Hide the popup on success" option back on did not change anything.

This issue has persisted for multiple days, over multiple system reboots.

I am on Windows 7 Professional, using Python 3.4.2 and Livestreamer 1.11.1.

Even with this issue, yours is by far the best Livestreamer gui I have used, and I very much appreciate your work. While I am at it, I would also like to request an option to have the program display in the taskbar when open, but minimize to the tray, as that would be my ideal configuration. Thank you for your time.

**Comment by bastimeyer** [comment] 2015-01-28 05:02
Thanks!

The stream launch logic has been rewritten in the latest release, but I haven't seen any problems with the closing popup setting yet and I'm also unable to reproduce the issue you described above.
The application cache and settings are saved in `%LOCALAPPDATA%\livestreamer-twitch-gui` on windows. You could delete it in order to reset your settings, but I don't think that this will help, since [I didn't touch the settings](https://github.com/bastimeyer/livestreamer-twitch-gui/compare/v0.6.1...v0.7.0#diff-5ec2dc23e53c40cc4a163d5d9af04101R14) since v0.6.1...

> While this was in effect, the popup stayed at "Launching stream" and did not progress to giving me the option to open chat, etc.

The popup closing logic actually has nothing to do with the stream launch logic, so I don't know how disabling/reenabling this could have different effects on launching streams. There seems to be another issue here or maybe on your machine or your livestreamer installation/configuration, idk :worried: 
The popup will only be closed after everything else has succeeded, see [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.7.0/src/app/controllers/LivestreamerController.js#L157) and [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.7.0/src/app/controllers/LivestreamerController.js#L172).


> While I am at it, I would also like to request an option to have the program display in the taskbar when open, but minimize to the tray, as that would be my ideal configuration.

Yeah, this could be implemented quite easily. Right now, you can just click on the tray icon for minimizing the window to the tray.

**Comment by speccer** [comment] 2015-01-28 23:18
If you can't reproduce it, then it should probably just be chalked up to the quirks of my somewhat aged system. Sorry about that. I had exhausted the solutions I could think of and posted here in the event it wasn't a localized issue; I'm by no means an expert. Thanks for looking into it.

And thank you for the minimize to tray tip! I hadn't noticed that feature.

**Comment by appleiiguy** [comment] 2015-01-30 03:03
I also get the same issue on my Mac. livestreamer is version livestreamer-1.11.1 and I have tried 32-bit and 64-bit builds. I am unable to minimize the Gui, livestreamer Gui doesn't show in the dock. It does show in the task-bar but there is no minimize option. It also doesn't auto-open chat even though that was working before I updated.
![screenshot_37](https://cloud.githubusercontent.com/assets/10767155/5970532/6ed9e898-a7e9-11e4-9a77-216c043559b5.jpg)

**Comment by bastimeyer** [comment] 2015-01-30 04:13
Could you please post the `stdout` and `stderr` of livestreamer when launching a stream from the shell?

You're stuck at "Launching stream" during the launch sequence, because it seems that livestreamer is never emitting the `Starting player: XYZ` message. Since v0.7.0, [this is the requirement](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.7.0/src/app/controllers/LivestreamerController.js#L374-L402) for succeeding the launch procedure. Before then the output of livestreamer didn't have any impact on the GUI and the popup was just silently closed in case of an error. But here it seems that livestreamer is behaving a little bit unexpected...
The chat will be opened after the message has been received, so that's the reason for the auto-open-chat to fail.

**Comment by appleiiguy** [comment] 2015-01-30 10:34
This is the output I see in terminal when launching a stream.
[cli][info] Found matching plugin twitch for URL http://www.twitch.tv/fireytoad
[plugin.twitch][info] Attempting to authenticate using OAuth token
[plugin.twitch][info] Successfully logged in as AppleIIGuy
[cli][info] Available streams: audio, source (worst, best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC
[cli][info] Player closed
[cli][info] Stream ended

**Comment by bastimeyer** [comment] 2015-01-30 12:07
Hm, interesting... Could you please disable the twitch auth in your livestreamer config and see if then works correctly? I think it won't make any difference, but it's worth a try.
If it doesn't, could you please debug the application for me? As I already said, I'm unable to reproduce this on windows, osx and linux... Please tell me if you're willing to do so, so I can tell you what to do.

**Comment by appleiiguy** [comment] 2015-01-30 14:22
it's now working for me.. Which is weird.. Chat now pops up in Firefox and the windows now minimizes to the task bar.

**Comment by bastimeyer** [comment] 2015-01-30 14:30
So was it because of the auth stuff or what did you change?

**Comment by bastimeyer** [comment] 2015-01-30 14:34
What did you do differently then? Was it the auth stuff or how did you start the application before when the popup did not work correctly? I'd like to know how to reproduce this bug...

**Comment by appleiiguy** [comment] 2015-01-30 15:31
I left auth on. The only other change I could think that I did today was update livestreamer just to be sure it was the latest.

**Comment by appleiiguy** [comment] 2015-01-31 06:30
Ok i figured out how I was able to replicate the bug.
when I have firefox opened but all windows closed. Then the gui has the problem where the window doesnt close. If firefox has a browser window open it closes. If firefox is closed it starts firefox and the chat and works correctly.

**Closed** 2015-02-07 23:46 UTC

**Comment by skulblakka** [comment] 2015-04-23 21:25
I am having the same issue. The popup is stuck at "Waiting for livestreamer to start the stream" and never disappears. [Image](http://i.imgur.com/63Zp8Ty.png)

I started using the gui about a month ago and it never worked (although I never knew that it was supposed to do something different than staying on the "Launching stream" screen) 

I am using Windows 8.1, Python 3.4.0 and I updated both livestreamer and the gui to the newest commit on git.

**Comment by bastimeyer** [comment] 2015-04-23 21:37
@skulblakka Did you install livestreamer via pip on Windows? See #19

**Comment by speccer** [comment] 2015-04-23 22:16
It's possible that's what my initial problem was. I recently moved to Windows 8.1 -- this go-around I installed livestreamer with the executable, and I've been able to use v0.7.3 of the gui without issue.

**Comment by skulblakka** [comment] 2015-04-23 22:19
I guess installing via the setup script in the source code is basically the same as installing via pip, right?

**Comment by bastimeyer** [comment] 2015-04-23 22:36
I don't know, could be possible though. Just use the livestreamer [installer](https://github.com/chrippa/livestreamer/releases) and it should be fine.

**Comment by skulblakka** [comment] 2015-04-23 22:59
Ok. Thanks for the help!
