### ISSUE TITLE
VLC is unable to open the MRL

### ISSUE THREAD

**Issue by GumboMKX** [bastimeyer/livestreamer-twitch-gui#301] opened 2016-08-23 20:04 UTC
I have been messing around with this for the past two hours and I can't figure out what's going wrong?  Everything has been working great and then today, I try and connect to the same stream I watched before and I get the error message:

Your input can't be opened:
VLC is unable to open the MRL 'http://0.1.0.6:4071/'. Check the log for details.

I'm not sure where to check the log files for VLC but this is what I can say for what I have done.
I'm using an older system, Windows XP 32-Bit for the streams and so far, I have uninstalled and reinstalled the newest version of VLC: vlc-2.2.4-win32.exe.  After I reinstalled VLC, I added it to my firewall to make sure it was unblocked.

I downloaded, uninstalled and reinstalled livestreamer-v1.12.2-win32-setup.exe and I didn't change any options in the edit file.  I then deleted, downloaded and reinstalled livestreamer-twitch-gui-v0.14.2-win32.zip.

I ran the livestreamer-twitch-gui-v0.14.2-win32 program and checked the settings. The player and the chat tabs show the programs listed but Livestreamer is blank for the executable location.  I tried entering the software location but still get the same error.  I have all the software installed to the same directory as well but I'm still getting the same error... Help please!

**Comment by bastimeyer** [comment] 2016-08-24 05:22
So this sounds like the same issue as #300, but with more infos, thanks.
This also sounds like a livestreamer related issue, but let's see...

Does it work when just using livestreamer from the shell? By default, the GUI will use the [`--player-passthrough http`](http://docs.livestreamer.io/cli.html#cmdoption--player-passthrough) livestreamer parameter (and a couple of other parameters). I can see that you didn't change that.
Could you please try to run this and see if it's working correctly:
`livestreamer --player-passthrough http twitch.tv/CHANNEL best`

Since I'm unable to reproduce this and since you're using Windows, I may have to ask if your firewall or something else is blocking livestreamer's http streaming relay server.

**Comment by GumboMKX** [comment] 2016-08-24 18:54
I checked my firewall and I have Livestreamer and Livestreamer-Twitch-GUI added and unblocked.
I tried running Livestreamer with the command you gave me and I get the following error.

D:\livestreamer-twitch-gui-v0.14.2-win32\livestreamer-twitch-gui>livestreamer --
player-passthrough http http://www.twitch.tv/CHANNEL best
[cli][info] Found matching plugin twitch for URL http://www.twitch.tv/CHANNEL
[cli][info] Available streams: audio, high, low, medium, mobile (worst), source
(best)
[cli][info] Opening stream: source (hls)
error: The default player (VLC) does not seem to be installed. You must specify
the path to a player executable with --player.

I know I have VLC (D:\Program Files\VideoLAN\VLC) installed but if you can give me the command line then I will try it with it linking to VLC.

**Comment by bastimeyer** [comment] 2016-08-24 18:59
> error: The default player (VLC) does not seem to be installed. You must specify the path to a player executable with --player.

`livestreamer --player-passthrough http --player "D:\Program Files\VideoLAN\VLC\vlc.exe" twitch.tv/CHANNEL best`

https://github.com/chrippa/livestreamer/blob/develop/win32/livestreamerrc#L4-L10
https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Player-configuration#default-player

**Comment by GumboMKX** [comment] 2016-08-24 19:24
I'm starting to think this might have been a problem on Twitch side because everything is working again.

I replied to your message, Bastimeyer and I decided to test it out so I loaded up livestreamer-twitch-gui through the windows directory.  I connected to the stream and everything loaded correctly.  I even noticed the http changed from 'http://0.1.0.6:4071/' to http://127.0.0.1:1112/ which is what the stream link http was before.

I'll keep an eye on it and will write back if I have issues again but thanks again for helping out and for the sweet software.

**Comment by bastimeyer** [comment] 2016-08-24 19:30
> changed from 'http://0.1.0.6:4071/' to http://127.0.0.1:1112/

If this issue persists, then you should report it on the [livestreamer repo](https://github.com/chrippa/livestreamer), as it is completely unrelated to the GUI.

I'm closing this for now. If you think that a misconfiguration of the default settings of the GUI is causing this, please feel free to reopen.

**Closed by bastimeyer** 2016-08-24 19:30 UTC
