### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Yaya7** [bastimeyer/livestreamer-twitch-gui#271] opened 2016-07-17 20:59 UTC
I tiried to push the stream to flv by using ffmpeg but giving erorr any help please
i want to push the video twitch rtmp can someone help me 
livestreamer "hlsvariant://http://hlslinear-l3c.med1.foxsportsgo.com/ls02/foxsports/FOX_SPORTS_2/live/master_wired_web_ads.m3u8" best --player | ffmpeg -i - -acodec aac -strict -2 -ab 48000 -ar 48000 -vcodec copy -f flv "rtmp://"

**Comment by bastimeyer** [comment] 2016-07-17 21:48
Why do you first open an issue on the correct repo and afterwards come here to the **wrong** one after ignoring not only the name, but also everything else like the issue template and contribution guidelines?Even on the livestreamer repo, you're misusing the issue system for your personal stuff that is clearly not a bug an could be resolved by reading the manual... I'll probably regret this, but you're looking for the `-O` parameter instead of `--player`. Good night...

**Closed by bastimeyer** 2016-07-17 21:48 UTC
