### ISSUE TITLE
[duplicate] filter all channels by games

### ISSUE THREAD

**Issue by FlareGunz** [bastimeyer/livestreamer-twitch-gui#320] opened 2016-09-28 14:52 UTC
I have no Knowledge about python, so id ask if its possible to make a filter-like to games, as a way to remove the LoL and Dota streams Spam there is out there.

sometimes, im just looking for a non-moba game to watch and its hard to find.

**Comment by bastimeyer** [comment] 2016-09-28 15:41
Duplicate of #193 and #199...

This question has been asked several times now. Unfortunately, this is not possible due to the Twitch API not having a filter parameter.
Before you ask, doing any filtering locally on the client side after retrieving all unfiltered data from the API is not going to be implemented. [Here](https://github.com/bastimeyer/livestreamer-twitch-gui/issues/151#issuecomment-183581175) you can read a more detailed explanation about that related to filtering multiple stream languages, which was once supported but got removed from the Twitch API.

Btw, the application is not written in python... Excerpt from the header of the readme:
> Livestreamer Twitch GUI is a NW.js application, which means that it is a web application written in JavaScript (EmberJS), HTML (Handlebars) and CSS (LessCSS) and is being run by a Node.js powered version of Chromium.

**Comment by FlareGunz** [comment] 2016-09-28 16:03
Oh, i searched and didn't found this other before.

Thanks for your time to explain.

**Closed** 2016-09-28 16:05 UTC
