### ISSUE TITLE
Error when chosing a Stream

### ISSUE THREAD

**Issue by xNexis** [bastimeyer/livestreamer-twitch-gui#297] opened 2016-08-19 00:25 UTC
### Description
As soon as i chose a Stream in the GUI i get that Error

//NOT FOR EVERY STREAM

### Expected / Actual behavior
Start the Stream

### Reproduction steps

1. Start the Gui
2. Chose a Stream
3. no profit

### Environment details (operating system, etc.)

Windows 10 64bit

### Comments, logs, screenshots, etc.

Traceback (most recent call last):
File "<string>", line 6, in <module>
File "__main__.py", line 128, in <module>
File "__main__livestreamer__.py", line 9, in <module>
File "livestreamer_cli\main.py", line 886, in main
File "livestreamer_cli\main.py", line 491, in handle_url
File "livestreamer_cli\main.py", line 374, in handle_stream
File "livestreamer_cli\main.py", line 141, in output_stream_http
File "livestreamer_cli\output.py", line 21, in open
File "livestreamer_cli\output.py", line 123, in _open
File "livestreamer_cli\output.py", line 138, in _open_subprocess
File "livestreamer_cli\output.py", line 116, in _create_arguments
File "shlex.py", line 279, in split
File "shlex.py", line 269, in next
File "shlex.py", line 96, in get_token
File "shlex.py", line 172, in read_token
ValueError: No closing quotation

**Comment by bastimeyer** [comment] 2016-08-19 02:13
This looks like the same issue as #256...
Do you have custom player arguments set in the GUI?

**Comment by xNexis** [comment] 2016-08-19 02:16
Yea i fixed it by removing them

**Comment by bastimeyer** [comment] 2016-08-19 02:25
Could you please post your not working player arguments?
I want to make sure that it is really the same error as #256...

If you're using variables in the player arguments string, you could try removing the quotation marks around the variables. This will escape every character, but not every player will be able to read the parameters correctly.

**Comment by xNexis** [comment] 2016-08-19 02:33
If i use variables = sometimes the error in the first post comes, if not, VLC player says it cant read the file.
used variables: {name} - {status} - {online} - {delay}

**Comment by bastimeyer** [comment] 2016-08-19 02:38
This issue is a duplicate of #256, closing this here now. It's a bug of the command line parser of livestreamer on Windows...
If there's anything useful to add, please post it there. Thanks.

**Closed by bastimeyer** 2016-08-19 02:38 UTC
