### ISSUE TITLE
My streams section stream thumbnails duplication issue

### ISSUE THREAD

**Issue by ptkovsky** [bastimeyer/livestreamer-twitch-gui#216] opened 2016-02-13 15:50 UTC
Hello. I noticed a strange issue that came up for me recently. I've been getting this few times so far. So when I open my streams section sometimes it happens that some stream thumbnails or links to them or whatever this is called duplicate themselves. For example, now I got this going for Zeus stream link http://imgur.com/77JRHNI. I'm not sure how to reproduce it, but I thought that it would be worth making this report here anyway. Got this yesterday with different stream. Tried searching for something similar here. Any ideas?

**Comment by bastimeyer** [comment] 2016-02-13 16:08
This can happen when the viewer count of a stream gets updated between multiple API requests and a stream has fallen behind another one in the ranking. That's a common issue with infinite scroll implementations. New items could be checked for being a duplicate of an already existing item, but I think it's not too dramatic.

The viewer counts are updated by Twitch every minute or so. When you're scrolling through a menu and you're making several requests in a short period of time, it's very unlikely that this kind of error is happening. If you're waiting for a longer time though before scrolling again, other streams might overtake already loaded ones, so they are pushing the loaded ones down in the ranking, making them re-appear on the next request. This is how it works...

**Closed** 2016-03-02 23:22 UTC
