### ISSUE TITLE
player-args: quoting and other issues

### ISSUE THREAD

**Issue by InfernoZeus** [bastimeyer/livestreamer-twitch-gui#77] opened 2015-04-25 12:31 UTC
I've been testing out the player-args option that was added in v0.8.0 and I'm having trouble getting it to work. The use case for me is related to [Livestreamer's issue 258](https://github.com/chrippa/livestreamer/issues/253) which requires setting VLC to use ALSA output.

Using Livestreamer directly, I have to add the following option for it to work:

    --player-args '--aout alsa {filename}'

Adding the same thing in to the option field (with quotes), seems to work, but the player never launches, and the little popup dissapears. Remove the quotes, and the popup stays, but the player still doesn't appear. Remove the `{filename}` and the player loads up, but unsurprisingly never tries to load the stream.

I'm not sure exactly what the solution to this should be. Should livestreamer-twitch-gui add the quotes and `{filename}` or is the end user required to know that livestreamer expects that to be present?

**Comment by InfernoZeus** [comment] 2015-04-25 12:32
Note, there's [a comment from chrippa here](https://github.com/chrippa/livestreamer/issues/714#issuecomment-72322163) that implies the `{filename}` is required.

**Comment by bastimeyer** [comment] 2015-04-25 13:00
> Note, there's a comment from chrippa here that implies the {filename} is required.

Right, whenever you set the `--player-args` parameter, you also have to specify the `{filename}` variable (as pointed out in the livestreamer documentation).

> I'm having trouble getting it to work

Which parameter values did you use? What you are trying to do can be achieved using these values:
**--player:** `/usr/bin/vlc`
**--player-args:** `--aout alsa --meta-title="{name} - {game} - {status}" {filename}`

**Comment by InfernoZeus** [comment] 2015-04-25 15:55
Using those exact values in the options fields doesn't work. What's the easiest way to get a debug log? Launching from shell doesn't show the traceback.

**Comment by bastimeyer** [comment] 2015-04-25 16:22
> I wasn't sure if it was expected that a user of livestreamer-twitch-gui would know about livestreamers options

I know, that's why the user needs to turn on the advanced settings first in order to access this feature. The parameters listed below the description are also linked to the docs if there's anything unclear.

> What's the easiest way to get a debug log? 

[Start the application in debug mode](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.8.0/CONTRIBUTING.md#developing-and-building) and set a breakpoint [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.8.0/src/app/controllers/LivestreamerController.js#L325) (or [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.8.0/src/app/models/Livestreamer.js#L50)). [Here's](https://iojs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) also a link to the io.js child_process.spawn documentation.

**Comment by InfernoZeus** [comment] 2015-04-26 12:09
> that's why the user needs to turn on the advanced settings first in order to access this feature.

Oops, I missed that :)

I'll try getting a debug log now.

**Comment by InfernoZeus** [comment] 2015-04-26 13:50
Hmm.. I tried following those instructions, but I get the following error when running `grunt dev`:
```
Running "requirejs:dev" (requirejs) task
{ [Error: Error: Module loading did not complete for: main, app
    at Function.build.checkForErrors (/home/ben/Development/livestreamer-twitch-gui/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:28424:19)
]
  originalError: [Error: Module loading did not complete for: main, app] }
```
Any idea what's up? :/

**Comment by bastimeyer** [comment] 2015-04-26 14:12
> Error: Module loading did not complete for: main, app

I'm having the same error when I try to build it in one of my OSX VMs. Still haven't figured out why this is happening.

**Comment by bastimeyer** [comment] 2015-04-26 18:05
I think I tracked down the issue, but I don't know why this is happening.
It's the jquery dependency of ember. For some reason, requirejs (r.js actually) is throwing the error while loading the jquery module.

If you still want to debug your issue, just run the application from the source files without compiling it. Just have a look at CONTRIBUTING.md.

If you find a solution to the build error, feel free to open another thread or even PR :smiley:

**Comment by bastimeyer** [comment] 2015-04-28 16:36
Did you find out why this wasn't working for you?

**Comment by InfernoZeus** [comment] 2015-04-28 17:01
Sorry, I haven't had a chance to look at it yet. I should have some time
this weekend.

**Comment by bastimeyer** [comment] 2015-05-19 16:43
Did you manage to find the cause of this issue?

**Comment by VirtualPorygon** [comment] 2015-05-31 21:40
Hi!

It's me again. I just wanted to say that I got exactly the same error. The thing is that I managed to compile the sources several time but recently (since the last version 0.9.1 I think) and only on my laptop it doesn't work. I tried to check the package on my main computer and my laptop but there is no real differences. Here is the error:

>Running "requirejs:release" (requirejs) task
{ [Error: Error: Module loading did not complete for: main, app
    at Function.build.checkForErrors (/home/NAME/livestreamer-twitch-gui/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:29387:19)
]
  originalError: [Error: Module loading did not complete for: main, app] }

So as you suggested I tried to debug the program but I never did this and I don't really know what to do.  Could you please tell me what command I need to run to debug it correctly because I'm sure that what I did is totally wrong. Here are the few commands that I managed to understand.
- I ran grunt metadata less:source and grunt less:source watch:lesssource
- Then I don't know what to do, I tried a lot of things, the only thing that gave me a result was:
"nodejs nwGui.js" or any of the js file. Here is the result:

>/home/NAME/livestreamer-twitch-gui/src/app/nwjs/nwGui.js:1
(function (exports, require, module, __filename, __dirname) { define( [], func
                                                              ^
ReferenceError: define is not defined
    at Object.<anonymous> (/home/NAME/livestreamer-twitch-gui/src/app/nwjs/nwGui.js:1:63)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

I read this page https://github.com/nwjs/nw.js/wiki/Getting-Started-with-nw.js as suggested but I didn't really helped me. 
I'm on Ubuntu 15.04 64bits and my other computer too, but it's strange that I managed to compile the code with my other computer and not with the laptop.

Thanks in advance for the help!

**Comment by bastimeyer** [comment] 2015-06-01 03:07
@VirtualPorygon 
Yeah, this build-issue does still exist and it's probably a requirejs/r.js related bug. I'm getting the same error when trying to build the application in some of my VMs and on my notebook as well.
I'm going to open another thread for this issue, so it can be discussed/solved over there...

I'm also closing this thread for now...

**Closed by bastimeyer** 2015-06-01 03:07 UTC
Labels: unconfirmed

**Comment by ben-foxmoore** [comment] 2015-06-01 11:47
@bastimeyer @VirtualPorygon Hey guys, sorry for the lack of activity in this discussion. I just don't have enough knowledge/experience of node/io.js and the various build tools/frameworks around it to really look into it in depth.

**Comment by InfernoZeus** [comment] 2015-06-01 12:09
I also may have commented with the wrong user....
