### ISSUE TITLE
Portable? feature reques

### ISSUE THREAD

**Issue by 00xe** [bastimeyer/livestreamer-twitch-gui#253] opened 2016-05-24 22:01 UTC
hey. Since you can run and download livestreamer and gui via zip archives on windows, why can't you make it portable? Maybe somekind a simple solution for that? I've tried to set custom location for live streamer in settings "%CD%\livestreamer-v1.12.2", but it doesn't work. I think i need to do something else and run it via bat.. 

Portable apps are popular now days so as twich is. A simple yet portable solution would be awesome. Can we except something like that?

Sorry for my bad English.

**Comment by 00xe** [comment] 2016-05-24 22:02
or just point me, how to make it portable please. I've read wiki and guides but haven't found anything about twich-gui being portable. Thanks.

**Comment by bastimeyer** [comment] 2016-05-24 22:17
Duplicate of #237

**Closed by bastimeyer** 2016-05-24 22:17 UTC
